version: '3.2'
services:
  cakephp-backend:
    image: sarawutt/php7-apache
    volumes:
      - D:/ANGULAR/PAKGON_TRAINING/DEMO_CAKEPHP3_ANGULAR6/CAKEPHP3-BACKEND/www:/var/www/html
    ports:
      - "7200:80"
      - "7243:443"
    depends_on:
      - db

  db:
    image: postgres:9.4-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: password